const promptDirectory = new URL("../supabase/prompts/", import.meta.url);
const outputFile = new URL(
  "../supabase/functions/_shared/ai/generated_prompts.ts",
  import.meta.url,
);

const prompts = [
  ["conversationReplyV1", "conversation_reply_v1.md"],
  ["goldenBookExtractV1", "golden_book_extract_v1.md"],
  ["realLifeExtractV1", "real_life_extract_v1.md"],
  ["realLifeReconstructV1", "real_life_reconstruct_v1.md"],
  ["realLifeReconstructV2", "real_life_reconstruct_v2.md"],
  ["realLifeReconstructV3", "real_life_reconstruct_v3.md"],
  ["responseChallengeSessionV1", "response_challenge_session_v1.md"],
  ["responseEvaluateV2", "response_evaluate_v2.md"],
  ["responseEvaluateV3", "response_evaluate_v3.md"],
  ["scenarioGenerateV2", "scenario_generate_v2.md"],
  ["scenarioGenerateV3", "scenario_generate_v3.md"],
  ["scenarioPersonalizeV1", "scenario_personalize_v1.md"],
  ["scenarioPersonalizeV2", "scenario_personalize_v2.md"],
  ["scenarioSafetyReviewV1", "scenario_safety_review_v1.md"],
  ["scenarioSafetyReviewV2", "scenario_safety_review_v2.md"],
] as const;

const sections = await Promise.all(prompts.map(async ([name, file]) => {
  const prompt = await Deno.readTextFile(new URL(file, promptDirectory));
  const lines = prompt.split("\n").map((line) => `  ${JSON.stringify(line)},`);
  return [
    `export const ${name} = [`,
    ...lines,
    `].join("\\n");`,
  ].join("\n");
}));

const generated = [
  "// Generated by scripts/generate_ai_prompts.ts. Do not edit manually.",
  "",
  sections.join("\n\n"),
  "",
].join("\n");

if (Deno.args.includes("--check")) {
  const current = await Deno.readTextFile(outputFile);
  if (current !== generated) {
    throw new Error(
      "Generated AI prompts are stale. Run: deno run --allow-read --allow-write scripts/generate_ai_prompts.ts",
    );
  }
} else {
  await Deno.writeTextFile(outputFile, generated);
}
